semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: avoid
#parser: typescript
insertPragma: true
proseWrap: always
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: true
